In [ ]:
import pandas as pd
df = pd.read_csv("/content/uber_trips_dataset_50k.csv")

In [ ]:
df.head()

,trip_id,driver_id,rider_id,city,pickup_lat,pickup_lng,drop_lat,drop_lng,distance_km,fare_amount,status,payment_method,pickup_time,drop_time
0,1,8270,10683,San Francisco,37.170931,-77.586479,37.173652,-77.619934,2.97,10.71,Completed,Wallet,2023-01-01 00:00:00,2023-01-01 00:08:54.600000000
1,2,1860,44743,Boston,38.898127,-108.582977,38.937464,-108.558727,8.43,22.41,Completed,UPI,2023-01-01 00:01:00,2023-01-01 00:26:17.400000000
2,3,6390,75839,San Francisco,38.814571,-89.942603,38.821702,-89.896435,5.46,12.91,Completed,Cash,2023-01-01 00:02:00,2023-01-01 00:18:22.800000000
3,4,6191,22189,New York,37.295906,-75.328844,37.301375,-75.317488,6.61,15.70,Completed,Wallet,2023-01-01 00:03:00,2023-01-01 00:22:49.800000000
4,5,6734,61104,Seattle,38.972395,-121.482913,38.992088,-121.467904,10.50,19.15,Completed,Wallet,2023-01-01 00:04:00,2023-01-01 00:35:30.000000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   trip_id         50000 non-null  int64
 1   driver_id       50000 non-null  int64
 2   rider_id        50000 non-null  int64
 3   city            50000 non-null  object
 4   pickup_lat      50000 non-null  float64
 5   pickup_lng      50000 non-null  float64
 6   drop_lat        50000 non-null  float64
 7   drop_lng        50000 non-null  float64
 8   distance_km     50000 non-null  float64
 9   fare_amount     50000 non-null  float64
 10  status          50000 non-null  object
 11  payment_method  50000 non-null  object
 12  pickup_time     50000 non-null  object
 13  drop_time       50000 non-null  object
dtypes: float64(6), int64(3), object(5)
memory usage: 5.3+ MB

In [ ]:
df.shape

(50000, 14)

In [ ]:
df.columns

Index(['trip_id', 'driver_id', 'rider_id', 'city', 'pickup_lat', 'pickup_lng',
       'drop_lat', 'drop_lng', 'distance_km', 'fare_amount', 'status',
       'payment_method', 'pickup_time', 'drop_time'],
      dtype='object')

In [ ]:
df.describe()

,trip_id,driver_id,rider_id,pickup_lat,pickup_lng,drop_lat,drop_lng,distance_km,fare_amount
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,25000.500000,5493.954540,55040.994580,38.998664,-97.485552,38.998768,-97.485677,7.008070,15.976205
std,14433.901067,2601.410798,25915.467105,1.155241,14.173744,1.155696,14.173735,2.946744,6.274406
min,1.000000,1000.000000,10001.000000,37.000009,-121.999465,36.953365,-122.047124,0.000000,1.080000
25%,12500.750000,3232.750000,32539.000000,37.994428,-109.818282,37.998237,-109.817260,4.980000,11.510000
50%,25000.500000,5497.000000,55164.000000,38.992589,-97.463042,38.994190,-97.464646,6.980000,15.430000
75%,37500.250000,7746.000000,77293.500000,39.999602,-85.190954,39.998849,-85.199652,9.000000,19.910000
max,50000.000000,9998.000000,99998.000000,40.999937,-73.001961,41.047536,-72.963476,19.410000,50.670000

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

trip_id           0
driver_id         0
rider_id          0
city              0
pickup_lat        0
pickup_lng        0
drop_lat          0
drop_lng          0
distance_km       0
fare_amount       0
status            0
payment_method    0
pickup_time       0
drop_time         0
dtype: int64

In [ ]:
df[['pickup_time', 'drop_time']].dtypes

pickup_time    object
drop_time      object
dtype: object

In [ ]:
df['pickup_time'] = pd.to_datetime(df['pickup_time'])
df['drop_time'] = pd.to_datetime(df['drop_time'])

df[['pickup_time', 'drop_time']].dtypes

pickup_time    datetime64[ns]
drop_time      datetime64[ns]
dtype: object

In [ ]:
#Why convert object to datetime?
#Right now, Python sees those columns as plain text, so it can't answer questions like:
#What is the busiest hour? Which day has the most rides? How many rides happened each month? What is the average ride duration?
#By converting them to datetime, you unlock all of those analyses.

**Phase 2: Feature Engineering**

Now we're going to create new columns from pickup_time. This is one of the most important steps because it makes time-based analysis much easier.

In [ ]:
df['pickup_hour'] = df['pickup_time'].dt.hour
df['pickup_day'] = df['pickup_time'].dt.day
df['pickup_month'] = df['pickup_time'].dt.month
df['pickup_weekday'] = df['pickup_time'].dt.day_name()

In [ ]:
df.head(10)

,trip_id,driver_id,rider_id,city,pickup_lat,pickup_lng,drop_lat,drop_lng,distance_km,fare_amount,status,payment_method,pickup_time,drop_time,pickup_hour,pickup_day,pickup_month,pickup_weekday
0,1,8270,10683,San Francisco,37.170931,-77.586479,37.173652,-77.619934,2.97,10.71,Completed,Wallet,2023-01-01 00:00:00,2023-01-01 00:08:54.600,0,1,1,Sunday
1,2,1860,44743,Boston,38.898127,-108.582977,38.937464,-108.558727,8.43,22.41,Completed,UPI,2023-01-01 00:01:00,2023-01-01 00:26:17.400,0,1,1,Sunday
2,3,6390,75839,San Francisco,38.814571,-89.942603,38.821702,-89.896435,5.46,12.91,Completed,Cash,2023-01-01 00:02:00,2023-01-01 00:18:22.800,0,1,1,Sunday
3,4,6191,22189,New York,37.295906,-75.328844,37.301375,-75.317488,6.61,15.70,Completed,Wallet,2023-01-01 00:03:00,2023-01-01 00:22:49.800,0,1,1,Sunday
4,5,6734,61104,Seattle,38.972395,-121.482913,38.992088,-121.467904,10.50,19.15,Completed,Wallet,2023-01-01 00:04:00,2023-01-01 00:35:30.000,0,1,1,Sunday
5,6,7265,84988,San Francisco,37.600551,-106.719069,37.556916,-106.730959,9.94,19.95,Completed,Card,2023-01-01 00:05:00,2023-01-01 00:34:49.200,0,1,1,Sunday
6,7,1466,82933,San Francisco,40.288560,-82.808219,40.278830,-82.844635,12.22,25.89,Completed,UPI,2023-01-01 00:06:00,2023-01-01 00:42:39.600,0,1,1,Sunday
7,8,5426,60182,Chicago,40.601188,-78.398733,40.569811,-78.368186,10.14,25.55,Completed,Cash,2023-01-01 00:07:00,2023-01-01 00:37:25.200,0,1,1,Sunday
8,9,6578,15826,San Francisco,40.296247,-87.576517,40.284638,-87.564783,1.88,7.97,Completed,Cash,2023-01-01 00:08:00,2023-01-01 00:13:38.400,0,1,1,Sunday
9,10,9322,63503,Boston,40.712634,-78.499656,40.670267,-78.477475,3.70,12.21,No-Show,UPI,2023-01-01 00:09:00,2023-01-01 00:20:06.000,0,1,1,Sunday

### Which city has the highest number of rides?

In [ ]:
df['city'].value_counts().idxmax()

'Boston'

### What is the average fare in each city?

In [ ]:
df.groupby('city')['fare_amount'].mean().sort_values(ascending=False)

city
Seattle          16.058910
Boston           16.052095
New York         16.048470
San Francisco    16.023240
Chicago          15.900960
Los Angeles      15.773431
Name: fare_amount, dtype: float64

### Which payment method is used the most?

In [ ]:
df['payment_method'].value_counts().idxmax() #gives the index of maximum payment method

'UPI'

In [ ]:
df['payment_method'].value_counts().max() #gives the count of maximum payment users

12549

In [ ]:
#extracting the duration of the ride from drop time to pickup_time
df['duration']= df['drop_time']-df['pickup_time']

In [ ]:
df.head()

,trip_id,driver_id,rider_id,city,pickup_lat,pickup_lng,drop_lat,drop_lng,distance_km,fare_amount,status,payment_method,pickup_time,drop_time,pickup_hour,pickup_day,pickup_month,pickup_weekday,duration
0,1,8270,10683,San Francisco,37.170931,-77.586479,37.173652,-77.619934,2.97,10.71,Completed,Wallet,2023-01-01 00:00:00,2023-01-01 00:08:54.600,0,1,1,Sunday,0 days 00:08:54.600000
1,2,1860,44743,Boston,38.898127,-108.582977,38.937464,-108.558727,8.43,22.41,Completed,UPI,2023-01-01 00:01:00,2023-01-01 00:26:17.400,0,1,1,Sunday,0 days 00:25:17.400000
2,3,6390,75839,San Francisco,38.814571,-89.942603,38.821702,-89.896435,5.46,12.91,Completed,Cash,2023-01-01 00:02:00,2023-01-01 00:18:22.800,0,1,1,Sunday,0 days 00:16:22.800000
3,4,6191,22189,New York,37.295906,-75.328844,37.301375,-75.317488,6.61,15.70,Completed,Wallet,2023-01-01 00:03:00,2023-01-01 00:22:49.800,0,1,1,Sunday,0 days 00:19:49.800000
4,5,6734,61104,Seattle,38.972395,-121.482913,38.992088,-121.467904,10.50,19.15,Completed,Wallet,2023-01-01 00:04:00,2023-01-01 00:35:30.000,0,1,1,Sunday,0 days 00:31:30

In [ ]:
df['duration'].mean()

Timedelta('0 days 00:21:01.452635999')

In [ ]:
#To find shortest ride
df['duration'].min()

Timedelta('0 days 00:00:00')

In [ ]:
#To find longest ride
df['duration'].max()

Timedelta('0 days 00:58:13.800000')

In [ ]:
df.groupby('city')['duration'].min()

city
Boston          0 days 00:00:01.800000
Chicago                0 days 00:00:00
Los Angeles     0 days 00:00:03.600000
New York        0 days 00:00:03.600000
San Francisco   0 days 00:00:01.800000
Seattle                0 days 00:00:00
Name: duration, dtype: timedelta64[ns]

In [ ]:
df.groupby('city')['duration'].max()

city
Boston          0 days 00:58:13.800000
Chicago         0 days 00:55:31.800000
Los Angeles     0 days 00:54:14.400000
New York               0 days 00:55:48
San Francisco   0 days 00:52:17.400000
Seattle                0 days 00:57:54
Name: duration, dtype: timedelta64[ns]

In [ ]:
df.groupby('city')['duration'].mean()

city
Boston          0 days 00:21:04.319659332
Chicago         0 days 00:20:53.096153385
Los Angeles     0 days 00:20:51.215177390
New York        0 days 00:21:02.538159330
San Francisco   0 days 00:21:05.563480538
Seattle         0 days 00:21:12.029715950
Name: duration, dtype: timedelta64[ns]

In [ ]:
#which city has the highest revenue?
df.groupby('city')['fare_amount'].sum().idxmax()

'Boston'

In [ ]:
df.groupby('city')['fare_amount'].sum().sort_values(ascending=False)
#This will rank all cities by revenue, which is useful for the report and Power BI dashboard.

city
Boston           135704.41
San Francisco    134611.24
Chicago          132693.51
New York         132351.73
Seattle          132293.30
Los Angeles      131156.08
Name: fare_amount, dtype: float64

**Report**: "Boston contributes the highest ride volume and total revenue. Uber should ensure sufficient driver availability in Boston, especially during peak hours, to maintain service quality and maximize revenue."

In [ ]:
#To check the status
df['status'].value_counts()

status
Completed    42540
Cancelled     4984
No-Show       2476
Name: count, dtype: int64

In [ ]:
# Calculate total rides per city
total_rides_per_city = df['city'].value_counts()

# Calculate cancelled rides (including 'No-Show') per city
cancelled_rides_per_city = df[df['status'].isin(['Cancelled', 'No-Show'])]['city'].value_counts()

# Calculate cancellation rate
cancellation_rate_per_city = (cancelled_rides_per_city / total_rides_per_city) * 100

# Display the cancellation rates sorted in descending order
display(cancellation_rate_per_city.sort_values(ascending=False))

city
Los Angeles      15.417919
Boston           15.046132
Chicago          15.026962
San Francisco    14.783954
New York         14.684128
Seattle          14.554504
Name: count, dtype: float64

In [ ]:
# Get the city with the highest cancellation rate
city_highest_cancellation_rate = cancellation_rate_per_city.idxmax()

print(f"The city with the highest cancellation rate is: {city_highest_cancellation_rate}")

The city with the highest cancellation rate is: Los Angeles

Task 1: Total Revenue by Payment Method

In [ ]:
df.groupby('payment_method')['fare_amount'].idxmax()

payment_method
Card      44255
Cash      41391
UPI       15666
Wallet     5874
Name: fare_amount, dtype: int64

In [ ]:
#average fare by payment method
df.groupby('payment_method')['fare_amount'].mean()

payment_method
Card      16.018265
Cash      15.966310
UPI       15.952572
Wallet    15.967591
Name: fare_amount, dtype: float64

### City Performance Summary

In [ ]:
# Calculate total revenue per city
total_revenue_per_city = df.groupby('city')['fare_amount'].sum()

# Calculate average fare per city
average_fare_per_city = df.groupby('city')['fare_amount'].mean()

# Calculate average duration per city
average_duration_per_city = df.groupby('city')['duration'].mean()

# Combine all metrics into a single DataFrame
city_performance_summary = pd.DataFrame({
    'Total Rides': total_rides_per_city,
    'Total Revenue': total_revenue_per_city,
    'Average Fare': average_fare_per_city,
    'Cancellation Rate (%)': cancellation_rate_per_city,
    'Average Ride Duration': average_duration_per_city
})

# Display the summary, sorted by Total Revenue for better insight
display(city_performance_summary.sort_values(by='Total Revenue', ascending=False))

,Total Rides,Total Revenue,Average Fare,Cancellation Rate (%),Average Ride Duration
city,,,,,
Boston,8454,135704.41,16.052095,15.046132,0 days 00:21:04.319659332
San Francisco,8401,134611.24,16.023240,14.783954,0 days 00:21:05.563480538
Chicago,8345,132693.51,15.900960,15.026962,0 days 00:20:53.096153385
New York,8247,132351.73,16.048470,14.684128,0 days 00:21:02.538159330
Seattle,8238,132293.30,16.058910,14.554504,0 days 00:21:12.029715950
Los Angeles,8315,131156.08,15.773431,15.417919,0 days 00:20:51.215177390

**Why I'm emphasizing this table**

Imagine an interviewer asks:

"Can you compare the performance of different cities?"

--Instead of opening five different charts, you can point to one summary table and explain:

Which city has the most rides.
Which city earns the most revenue.
Which city has the highest average fare.
Which city has the longest average distance.
Which city has the longest average ride duration.

| City                         | Observation                                              |
| ---------------------------- | -------------------------------------------------------- |
| **Boston**                   | Highest rides, highest revenue, strong overall performer |
| **Seattle**                  | Highest average fare and longest average ride duration   |
| **Los Angeles**              | Lowest average fare and highest cancellation rate        |
| **Chicago**                  | Shortest average ride duration                           |
| **San Francisco & New York** | Balanced performance across all metrics                  |

**Recommendation**

Boston is the strongest-performing market. Uber should ensure sufficient driver availability to maintain service quality and support continued growth.

Seattle appears to have higher-value rides on average. Uber could further analyze the factors contributing to these longer or higher-value trips.

Los Angeles should be investigated to understand why cancellations are comparatively higher and why average fares are lower.

In [ ]:
#To save the cleaned data
df.to_csv('uber_cleaned.csv', index=False)

In [ ]:
from google.colab import files

files.download('uber_cleaned.csv')

In [ ]:
df.columns

Index(['trip_id', 'driver_id', 'rider_id', 'city', 'pickup_lat', 'pickup_lng',
       'drop_lat', 'drop_lng', 'distance_km', 'fare_amount', 'status',
       'payment_method', 'pickup_time', 'drop_time', 'pickup_hour',
       'pickup_day', 'pickup_month', 'pickup_weekday', 'duration'],
      dtype='object')

In [ ]:
df['duration_minutes'] = df['duration'].dt.total_seconds() / 60

In [ ]:
df[['duration', 'duration_minutes']].head()

                duration  duration_minutes
0 0 days 00:08:54.600000              8.91
1 0 days 00:25:17.400000             25.29
2 0 days 00:16:22.800000             16.38
3 0 days 00:19:49.800000             19.83
4        0 days 00:31:30             31.50

In [ ]:
df.to_csv('uber_cleaned.csv', index=False)

In [ ]:
from google.colab import files
files.download('uber_cleaned.csv')

In [ ]:
print(df['duration_minutes'].dtype)

float64